### ISSUE TITLE
PeriVIS does not compile with Paraviw 5.8.1

### ISSUE THREAD

**Issue by jritta** [PeriVIS/PeriVIS#6]
**Description**
Compiling PeriVIS with Paraview version 5.8.1 leads to an error due to an unknown CMake command.

**Error Message**
```code
CMake Deprecation Warning at /usr/lib64/cmake/paraview/paraview-use-file-deprecated.cmake:1 (message):
  The `PARAVIEW_USE_FILE` is no longer used starting with 5.7.
Call Stack (most recent call first):
  io/LAMMPSTemporalReader/CMakeLists.txt:6 (INCLUDE)

CMake Error at io/LAMMPSTemporalReader/CMakeLists.txt:10 (ADD_PARAVIEW_PLUGIN):
  Unknown CMake command "ADD_PARAVIEW_PLUGIN".
```
**System**
- Fedora 32
- Paraview 5.8.1 (from official repository; package sources: paraview-5.8.1-4.fc32.src.rpm and paraview-5.8.1-4.fc32.src.rpm)
- CMake 3.17.4

**To Reproduce**
1. Compile the plug-in as described in [README.md](https://github.com/PeriVIS/PeriVIS/blob/master/README.md)

**Additional context**
I did some investigations on the problem. With Paraview 5.7  the developers changed the [CMake Plugin API](https://kitware.github.io/paraview-docs/nightly/cxx/PluginMigration.html) and some commands are deprecated amongst others also the ADD_PARAVIEW_PLUGIN command. Thus, I guess it does also not work for Paraview 5.7.x.
Here a thread in the paraview forum on this problem: https://discourse.paraview.org/t/paraview-5-8-unknown-cmake-command-add-paraview-plugin/4834

**Comment by diehlpk** [comment]
@jritta Sure, I can have a look at the CMake issues. 

Note that once the CMake issues is resolved, you need to compile Paraview since you can not use the pre-compiled one to load plugins.

**Comment by jritta** [comment]
@diehlpk Thank very much for your quick reply and the hint that I have to compile Paraview on my own to make use of the plug-in

**Comment by diehlpk** [comment]
@jritta I also have the source code from this paper

`Bussler M, Diehl P, Pflüger D, Frey S, Sadlo F, Ertl T, Schweitzer MA. Visualization of fracture progression in peridynamics. Computers & Graphics. 2017 Oct 1;67:45-57.`

somewhere on my external drive.

**Comment by jritta** [comment]
@diehlpk sounds great! Do you intend to publish it under a permissive software license?

**Comment by diehlpk** [comment]
@jritta Sure, however, this code will not compile with the latest Paraview version as well and needs some fixes.

@mbussler Do you have time to help out to get the code working again?

**Comment by jritta** [comment]
@diehlpk I would appreciate it!
I am not familiar with Paraview plugins programming, but maybe I can contribute to some bug fixes.

**Comment by diehlpk** [comment]
@jritta Sure, but I have the same issue that I have not done much with Paraview plugins either.

**Comment by diehlpk** [comment]
@jritta I was able to fix the two CMake issues in the branch `cmake-fixes`, see `filter/io/LAMMPSTemporalReader/`.

I had to change the folder structure and the CMakeLists.txt and now cmake runs and generates Make Files. However, the plugin is not compiled since, we have to add a new CMakeLists.txt to the new Plugin folder. 

I should look like this one here 

https://github.com/Kitware/ParaView/blob/master/Examples/Plugins/AddPQProxy/Plugin/CMakeLists.txt

Would be great if you could adapt all other plugins and I will have a look into the missing CMakeFile.

**Comment by jritta** [comment]
@diehlpk sure, I can do. That means similar changes as done in `filter/io/LAMMPSTemportalReader/CMakeLists.txt` must be done to all `CMakeLists.txt` in the other sub folders of the folder `filter`, right?

**Comment by diehlpk** [comment]
@jritta Yes, we have to add the new folder Plugin, copy all files expect of the CMakeLists.txt there, and update the CMakeLists.txt. I will look into the missing CMakeLists.txt over the weekend.

**Comment by diehlpk** [comment]
@jritta I had a look and preparing the code for ParaView >= 5.7 requires major changes for all the plugins. Since you have to compile ParaView yourself, I would recommend to use ParaView 5.3 since I see no benefit in using a newer ParaView.

I added the wont-fix label, since the effort is too much for the gain. Feel free to reopen the issues, if you think that a newer version is really needed,

**Comment by jritta** [comment]
@diehlpk okay thank you very much anyway!
